spring.jpa.hibernate.ddl-auto: none

spring.datasource.url: jdbc:mysql://${VRS_MYSQL:localhost}:3306/db_app?useSSL=false
spring.datasource.username: appuser
spring.datasource.password: TheP@ssw0rd

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml