# Database

spring.jpa.hibernate.ddl-auto: none
spring.h2.console.enabled: true

spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.url: jdbc:mysql://${ET_MYSQL:localhost}:3306/db_app?useSSL=false
spring.datasource.username: appuser
spring.datasource.password: TheP@ssw0rd

spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml